In [1]:
import pandas as pd
import numpy as np
import nltk
import string
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [2]:
import import_ipynb
import textPreprocessing

importing Jupyter notebook from textPreprocessing.ipynb


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/dheerajkumarbuchala/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/dheerajkumarbuchala/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/dheerajkumarbuchala/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [3]:
file_path = 'data/training-Obama-Romney-tweets.xlsx'

obama_df = pd.read_excel(file_path, sheet_name="Obama")
romney_df = pd.read_excel(file_path, sheet_name="Romney")

In [4]:
print(obama_df.head())

print("Initial no of tweets : " ,len(obama_df))

   Unnamed: 0                 date            time  \
0         NaN  2012-10-16 00:00:00  10:28:53-05:00   
1         NaN  2016-12-10 00:00:00  10:09:00-05:00   
2         NaN  2012-10-16 00:00:00  10:04:30-05:00   
3         NaN  2012-10-16 00:00:00  10:00:36-05:00   
4         NaN  2012-10-16 00:00:00  09:50:08-05:00   

                                     Anootated tweet Class  Your class label  
0  Kirkpatrick, who wore a baseball cap embroider...     0               NaN  
1  Question: If <e>Romney</e> and <e>Obama</e> ha...     2               NaN  
2  #<e>obama</e> debates that Cracker Ass Cracker...     1               NaN  
3  RT @davewiner Slate: Blame <e>Obama</e> for fo...     2               NaN  
4  @Hollivan @hereistheanswer  Youre missing the ...     0               NaN  
Initial no of tweets :  7198


In [5]:
print(romney_df.head())

print("Initial no of tweets : " ,len(romney_df))

   Unnamed: 0                 date            time  \
0         NaN  2012-10-16 00:00:00  09:38:08-05:00   
1         NaN  2012-10-16 00:00:00  10:22:34-05:00   
2         NaN  2012-10-16 00:00:00  10:14:18-05:00   
3         NaN  2012-10-16 00:00:00  09:27:16-05:00   
4         NaN  2012-10-16 00:00:00  10:11:43-05:00   

                                     Anootated tweet Class  Your class label  
0  Insidious!<e>Mitt Romney</e>'s Bain Helped Phi...    -1               NaN  
1  Senior <e>Romney</e> Advisor Claims <e>Obama</...     2               NaN  
2  .@WardBrenda @shortwave8669 @allanbourdius you...    -1               NaN  
3  <e>Mitt Romney</e> still doesn't <a>believe</a...    -1               NaN  
4  <e>Romney</e>'s <a>tax plan</a> deserves a 2nd...    -1               NaN  
Initial no of tweets :  7200


In [6]:
valid_classes = [-1, 0, 1]

In [7]:
# Pre-Processing the Obama DataFrame created
obama_df = obama_df[obama_df['Class'].isin(valid_classes)]
print("No of obama tweets after removing invalid classes : ", len(obama_df))

No of obama tweets after removing invalid classes :  5471


In [8]:
# Pre-Processing the Romney DataFrame created
romney_df = romney_df[romney_df['Class'].isin(valid_classes)]
print("No of romney tweets after removing invalid classes : ", len(romney_df))

No of romney tweets after removing invalid classes :  5648


In [9]:
obama_anootated_tweets = obama_df['Anootated tweet']
obama_assigned_class = obama_df['Class']

In [10]:
romney_anootated_tweets = romney_df['Anootated tweet']
romney_assigned_class = romney_df['Class']

In [11]:
obama_anootated_tweets = obama_anootated_tweets.tolist()
obama_assigned_class = obama_assigned_class.tolist()

In [12]:
romney_anootated_tweets = romney_anootated_tweets.tolist()
romney_assigned_class = romney_assigned_class.tolist()

In [13]:
obama_cleaned_tweets = textPreprocessing.dataClean(obama_anootated_tweets)
romney_cleaned_tweets = textPreprocessing.dataClean(romney_anootated_tweets)

In [14]:
obama_cleaned_tweets_final = textPreprocessing.tokenizationAndLemmatization(obama_cleaned_tweets)
romney_cleaned_tweets_final = textPreprocessing.tokenizationAndLemmatization(romney_cleaned_tweets)

In [15]:
test_file_path = 'data/sample-testdata.xlsx'

obama_test_df = pd.read_excel(test_file_path, sheet_name="Obama")
romney_test_df = pd.read_excel(test_file_path, sheet_name="Romney")

In [16]:
print(obama_test_df.head())
print("No of obama test tweets : ", len(obama_test_df))

   Unnamed: 0                 date            time  \
0         NaN  2012-10-16 00:00:00  10:28:53-05:00   
1         NaN  2016-12-10 00:00:00  10:09:00-05:00   
2         NaN  2012-10-16 00:00:00  10:04:30-05:00   
3         NaN  2012-10-16 00:00:00  10:00:36-05:00   
4         NaN  2012-10-16 00:00:00  09:50:08-05:00   

                                     Anootated tweet Class  Your class label  
0  Kirkpatrick, who wore a baseball cap embroider...     0               NaN  
1  Question: If <e>Romney</e> and <e>Obama</e> ha...     2               NaN  
2  #<e>obama</e> debates that Cracker Ass Cracker...     1               NaN  
3  RT @davewiner Slate: Blame <e>Obama</e> for fo...     2               NaN  
4  @Hollivan @hereistheanswer  Youre missing the ...     0               NaN  
No of obama test tweets :  7198


In [17]:
print(romney_test_df.head())
print("No of Romaney test tweets : ", len(romney_test_df))

   Unnamed: 0                                    Anootated tweet
0           1  Insidious!<e>Mitt Romney</e>'s Bain Helped Phi...
1           2  Senior <e>Romney</e> Advisor Claims <e>Obama</...
2           3  .@WardBrenda @shortwave8669 @allanbourdius you...
3           4  <e>Mitt Romney</e> still doesn't <a>believe</a...
No of Romaney test tweets :  4


In [18]:
obama_test_anootated_tweets = obama_test_df['Anootated tweet']
romney_test_anootated_tweets = romney_test_df['Anootated tweet']

In [19]:
obama_test_anootated_tweets = obama_test_anootated_tweets.tolist()
romney_test_anootated_tweets = romney_test_anootated_tweets.tolist()

In [20]:
obama_test_cleaned_tweets = textPreprocessing.dataClean(obama_test_anootated_tweets)
obama_test_cleaned_tweets_final = textPreprocessing.tokenizationAndLemmatization(obama_test_cleaned_tweets)

In [21]:
romney_test_cleaned_tweets = textPreprocessing.dataClean(romney_test_anootated_tweets)
romney_test_cleaned_tweets_final = textPreprocessing.tokenizationAndLemmatization(romney_test_anootated_tweets)

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
combined_training_tweets = obama_cleaned_tweets_final + romney_cleaned_tweets_final

In [27]:
combined_testing_tweets = obama_test_cleaned_tweets_final + romney_test_cleaned_tweets_final

In [28]:
max_features = 5000
tfidf_vectorizer = TfidfVectorizer(max_features=max_features)

In [29]:
tfidf_training_features = tfidf_vectorizer.fit_transform(combined_training_tweets).toarray()

# Create a DataFrame with TF-IDF features for training
tfidf_training_df = pd.DataFrame(tfidf_training_features, columns=tfidf_vectorizer.get_feature_names_out())

# Transform the vectorizer on the preprocessed testing tweets
tfidf_testing_features = tfidf_vectorizer.transform(combined_testing_tweets).toarray()

# Create a DataFrame with TF-IDF features for testing
tfidf_testing_df = pd.DataFrame(tfidf_testing_features, columns=tfidf_vectorizer.get_feature_names_out())

# Display the TF-IDF features for training and testing
print("TF-IDF Training Features:")
print(tfidf_training_df.head())

print("\nTF-IDF Testing Features:")
print(tfidf_testing_df.head())

TF-IDF Training Features:
   aaron   ab  abbas  abc  ability  able  abortion  abroad  absent  absentee  \
0    0.0  0.0    0.0  0.0      0.0   0.0       0.0     0.0     0.0       0.0   
1    0.0  0.0    0.0  0.0      0.0   0.0       0.0     0.0     0.0       0.0   
2    0.0  0.0    0.0  0.0      0.0   0.0       0.0     0.0     0.0       0.0   
3    0.0  0.0    0.0  0.0      0.0   0.0       0.0     0.0     0.0       0.0   
4    0.0  0.0    0.0  0.0      0.0   0.0       0.0     0.0     0.0       0.0   

   ...   yu  yuck  yum  yup  zach  zeleny  zelig  zero  zogby  zombie  
0  ...  0.0   0.0  0.0  0.0   0.0     0.0    0.0   0.0    0.0     0.0  
1  ...  0.0   0.0  0.0  0.0   0.0     0.0    0.0   0.0    0.0     0.0  
2  ...  0.0   0.0  0.0  0.0   0.0     0.0    0.0   0.0    0.0     0.0  
3  ...  0.0   0.0  0.0  0.0   0.0     0.0    0.0   0.0    0.0     0.0  
4  ...  0.0   0.0  0.0  0.0   0.0     0.0    0.0   0.0    0.0     0.0  

[5 rows x 5000 columns]

TF-IDF Testing Features:
   aaron  

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Step 4: Model Training

# Function to train a model
def train_model(X_train, y_train):
    model = LogisticRegression(max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    return model

# Function to evaluate a model on labeled data
def evaluate_model(model, X, y_true, candidate_name):
    # Make predictions on the data
    y_pred = model.predict(X)

    # Display evaluation results
    print(f"\n{candidate_name} Model Evaluation:")
    
    if y_true is not None:
        print("Classification Report:\n", classification_report(y_true, y_pred))

    return y_pred

# Replace the placeholders with your actual label data
obama_training_labels = obama_assigned_class  # Replace with actual labels
romney_training_labels = romney_assigned_class  # Replace with actual labels

# Train models for Obama and Romney
obama_model = train_model(tfidf_training_df.iloc[:len(obama_training_labels)], obama_training_labels)
romney_model = train_model(tfidf_training_df.iloc[len(obama_training_labels):], romney_training_labels)

# Make predictions on the testing data (no labels)
obama_testing_predictions = evaluate_model(obama_model, tfidf_testing_df.iloc[:len(obama_test_cleaned_tweets_final)], None, "Obama")
print(obama_testing_predictions)
romney_testing_predictions = evaluate_model(romney_model, tfidf_testing_df.iloc[len(obama_test_cleaned_tweets_final):], None, "Romney")
print(romney_testing_predictions)


Obama Model Evaluation:
[0 0 1 ... 0 0 1]

Romney Model Evaluation:
[-1 -1 -1 -1]


In [37]:
# Function to predict labels for test data
def predict_labels(model, X_test, candidate_name):
    # Make predictions on the test set
    predicted_labels = model.predict(X_test)

    # Display predicted labels
    print(f"\n{candidate_name} Predicted Labels:")
    print(predicted_labels)

    return predicted_labels

# Predict labels for Obama and Romney test data
obama_predicted_labels = predict_labels(obama_model, tfidf_testing_df.iloc[:len(obama_test_cleaned_tweets_final)], "Obama")
romney_predicted_labels = predict_labels(romney_model, tfidf_testing_df.iloc[len(obama_test_cleaned_tweets_final):], "Romney")



Obama Predicted Labels:
[0 0 1 ... 0 0 1]

Romney Predicted Labels:
[-1 -1 -1 -1]
